name: service-build
description: Base docker build action for the project microservices
inputs:
  service:
    description: Service to build
    required: true
  access_token:
    description: Token to authenticate with the container registry
    required: true
  sha:
    description: Commit sha which triggered the job
    required: true
  tag:
    description: Docker image tag
    required: true
runs:
  using: composite
  steps:
    - name: Docker build
      run: DOCKER_BUILDKIT=1 docker build -t ${{ inputs.service }} -f ./workspace-scripts/services/build/docker  --build-arg service=${{ inputs.service }} --build-arg dir=$(echo "${{ inputs.service }}" | cut -d'-' -f1) .
      shell: bash
    
    - name: Docker tag
      run: docker tag ${{ inputs.service }} ghcr.io/akalanka47000/${{ inputs.tag }}
      shell: bash

    - name: Docker login
      run: echo ${{ inputs.access_token }} | docker login ghcr.io -u akalanka47000 --password-stdin
      shell: bash

    - name: Docker push
      run: docker push ghcr.io/akalanka47000/${{ inputs.tag }}
      shell: bash

    - name: Update kube-config
      run: |
          git clone https://github.com/Akalanka47000/pharmaceutical-kube-config.git && cd pharmaceutical-kube-config
          sed -i "s/.*ghcr.io.*/          image: ghcr.io\/akalanka47000\/${{ inputs.tag }}/" deployment.yml

          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

          git config pull.ff true
          git add . && git commit -m "Synced with kube config" || true
          git pull --rebase && git push origin main

      shell: bash