export { default as NotFound } from './404';
export { default as Home } from './home';
export { default as Users } from './users';
export { default as Login } from './auth/login';
export { default as Register } from './auth/register';
export { default as Verify } from './auth/verify';
export { default as Products } from './product/products.jsx';
export { default as ProductForm } from './product/product-form.jsx';
export { default as Contact } from './contact';
export { default as Profile } from './profile';
export { default as Order } from './order';
export * from './auth';
export * from './product';
