name: frontend-build
on:
  push:
    branches:
      - main
    paths:
      - frontend/**
  workflow_dispatch:

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/service-build
        with:
          service: frontend
          tag: 'pharmaceutical-frontend:${{ github.sha }}-${{ github.run_attempt }}'
          access_token: ${{ secrets.REGISTRY_ACCESS_TOKEN }}
          repository_access_token: ${{ secrets.REPOSITORY_ACCESS_TOKEN }}
          build_args: ${{ secrets.FRONTEND_BUILD_ARGS }}
          dockerfile: './frontend/dockerfile'
