name: report-svc-test
on:
  pull_request:
    branches:
      - main
    paths:
      - services/report/**
      - packages/**
  workflow_dispatch:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/unit-test
        with:
          service: report-service
