name: user-service-build
on:
  push:
    branches:
      - main
    paths:
      - services/user/**
  workflow_dispatch:

jobs:
  docker-build:
    runs-on: ubuntu-latest
    container: docker:dind
    steps:
      - uses: ../actions/service-build
        with:
          service: user
          access_token: ${{ secrets.ACCESS_TOKEN }}